name: TownyWars
version: 1.1.5
authors: [ DanielRHarris ]
main: com.danielrharris.townywars.TownyWars
depend: [ Towny, CoreProtect ]
softdepend: [ CS-CoreLib, CSCoreLib, BossBarAPI ]
api-version: 1.13
commands:
  ideology:
    description: Set your ideology
  townideology:
    description: Check your ideology
  twar:
    usage: No permission!
  twar trade:
    description: Send a trade request
  twar neutral:
    permission: townywars.neutral
    usage: Syntax error! Perhaps you meant /twar neutral [nation]
  twar repair:
    permission: townywars.repair
  twar declare:
    description: Declare war on another town.
